name: "Lint moonscript project"
description: "Lints the moonscript project"
runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - uses: CFC-Servers/github_action_workflows/install_moonscript@feature/composite

    - uses: actions/checkout@v2
      with:
        repository: "CFC-Servers/cfc_moonc_lint_config"
        path: lint_config

    - name: Move config
      run: mv "$GITHUB_WORKSPACE/lint_config/lint_config.moon" "$GITHUB_WORKSPACE/"
      shell: bash

    - name: CD into project
      run: cd $GITHUB_WORKSPACE
      shell: bash

    - name: Build config
      run: moonc lint_config.moon && rm lint_config.moon
      shell: bash

    - name: Run and format linter
      run: |
        moonc -l . |
        sed "s/^\(line.*\)/${exc}[31m\1${exc}[0m/" |
        sed -E "s,^>(.*),echo \">\1\" | pygmentize -O full\,style=friendly -l moon -f 256,e"
      shell: bash
