env:
  projectUrl: 'CFC-Servers/cfc_report_processor'
  projectName: 'CFC Report Processor'
  projectBranch: 'master'
  projectWorkflow: build_and_deploy
  reviewers: |
    brandonsturgeon
    plally
