env:
  projectUrl: 'CFC-Servers/cfc_factions_backend'
  projectName: 'CFC Factions Backend'
  projectBranch: 'master'
  projectWorkflow: build_and_deploy
  reviewers: |
    brandonsturgeon
    plally
