name: Build and Deploy

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
      DOCKER_USERNAME:
        required: true
      DEPLOYMENT_DIR:
        required: true
      SSH_HOST:
        required: true
      SSH_USERNAME:
        required: true
      SSH_PRIVATE_KEY:
        required: true
      SSH_PORT:
        required: true
      DISCORD_WEBHOOK:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(git describe --abbrev=0 --tags `git rev-list --tags --max-count=1`)

      - name: Lowercase repository name
        id: repository_name
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ steps.repository_name.outputs.lowercase }}:latest
            ghcr.io/${{ steps.repository_name.outputs.lowercase }}:${{ steps.get_version.outputs.VERSION }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GH_TOKEN }}

  alerts:
    name: Send Discord alerts
    needs: build
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: technote-space/workflow-conclusion-action@v2

      - name: Alert on success
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[
            {
              "title": "**Job succeeded!**",
              "description": "[**${{ github.repository }}**](${{ github.server_url }}/${{ github.repository }})",
              "color": 4714567,
              "fields": [
                {
                  "name": "Job",
                  "value": "**[${{ github.workflow }} #${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})**",
                  "inline": true
                },
                {
                  "name": "Triggered by",
                  "value": "[${{ github.actor }}](${{ github.server_url }}/${{ github.actor }})",
                  "inline": true
                }
              ],
              "author": {
                "name": "GitHub Actions",
                "url": "${{ github.server_url }}/${{ github.repository }}/actions",
                "icon_url": "https://i.imgur.com/z0f8jOI.jpg"
              },
              "footer": {
                "text": "Status: ${{ env.WORKFLOW_CONCLUSION }}",
                "icon_url": "https://i.imgur.com/CzJAQiV.png"
              }
            }
          ]'
        if: env.WORKFLOW_CONCLUSION == 'success'

      - name: Alert on failure
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[
            {
              "title": "**Job failed!**",
              "description": "[**${{ github.repository }}**](${{ github.server_url }}/${{ github.repository }})",
              "color": 15746887,
              "fields": [
                {
                  "name": "Job",
                  "value": "**[${{ github.workflow }} #${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})**",
                  "inline": true
                },
                {
                  "name": "Triggered by",
                  "value": "[${{ github.actor }}](${{ github.server_url }}/${{ github.actor }})",
                  "inline": true
                }
              ],
              "author": {
                "name": "GitHub Actions",
                "url": "${{ github.server_url }}/${{ github.repository }}/actions",
                "icon_url": "https://i.imgur.com/z0f8jOI.jpg"
              },
              "footer": {
                "text": "Status: ${{ env.WORKFLOW_CONCLUSION }}",
                "icon_url": "https://i.imgur.com/O0I9Mmr.png"
              }
            }
          ]'
        if: env.WORKFLOW_CONCLUSION == 'failure' || env.WORKFLOW_CONCLUSION == 'timed_out'

