env:
  projectUrl: 'CFC-Servers/cfc_dynamic_limits'
  projectBranch: 'main'
  projectWorkflow: moonscript_release
  reviewers: |
    brandonsturgeon

name: 'CFC Dynamic Limits | Moonscript Release'

on:
  push:
    tags:
      - '*'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: workflows
          fetch-depth: 0

      - name: Get the workflow version
        id: workflow_versions
        run: |
          # Gets the names of the two latest tags
          cd "$GITHUB_WORKSPACE/workflows/"
          echo ::set-output name=VERSION::$(git describe --abbrev=0 --tags `git rev-list --tags --skip=0 --max-count=1`)
          echo ::set-output name=PREVIOUS_VERSION::$(git describe --abbrev=0 --tags `git rev-list --tags --skip=1 --max-count=1`)
          cd -

      - name: Get version diff link
        id: version_diff
        env:
          VERSION_DIFF: ${{ github.server_url }}/${{ github.repository }}/compare/${{ steps.workflow_versions.outputs.PREVIOUS_VERSION }}..${{ steps.workflow_versions.outputs.VERSION }}
        run: echo ::set-output name=VERSION_DIFF::$(echo "$VERSION_DIFF")

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ env.projectUrl }}
          token: ${{ secrets.GH_TOKEN }}
          path: project

      - name: Update workflow version
        run: |
          mkdir -p "$GITHUB_WORKSPACE/project/.github/workflows"
          cat "$GITHUB_WORKSPACE/workflows/workflows/${{ env.projectWorkflow }}.yml" > "$GITHUB_WORKSPACE/project/.github/workflows/${{ env.projectWorkflow }}.yml"

      - name: Open PR with changes
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          path: project
          commit-message: "Update ${{ env.projectWorkflow }} workflow to ${{ steps.workflow_versions.outputs.VERSION }}"
          branch: "update-workflow-${{ steps.workflow_versions.outputs.VERSION }}"
          delete-branch: true
          base: ${{ env.projectBranch }}
          title: "Update ${{ env.projectWorkflow }} workflow to ${{ steps.workflow_versions.outputs.VERSION }}"
          body: "This PR was automatically triggered due to [a change in the base `${{ env.projectWorkflow }}` workflow](${{ steps.version_diff.outputs.VERSION_DIFF }})"
          reviewers: ${{ env.reviewers }}
