name: Lint GLua

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y unzip liblua5.1-dev

      - name: Prepare GLuaFixer
        run: |
          cd $GITHUB_WORKSPACE
          curl -L https://github.com/FPtje/GLuaFixer/releases/download/1.20.0/glualint-1.20.0-linux.zip > glualint.zip
          unzip glualint.zip

      - name: Lint with GLuaFixer
        run: |
          ./glualint
