name: Lint GLua

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare GLuaFixer
        run: |
          cd $GITHUB_WORKSPACE
          curl -L https://github.com/FPtje/GLuaFixer/releases/download/1.18.3/glualint-1.18.3-linux.zip > glualint.zip

      - name: Extract GLuaFixer
        run: |
          cd $GITHUB_WORKSPACE
          unzip glualint.zip

      - name: Remove blacklisted folders
        run: rm -rvf lua/entities/gmod_wire_expression2/

      - name: Lint with GLuaFixer
        run: |
          ./glualint lint lua
