name: Lint GLua

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: project

      - name: Prepare GLuaFixer
        run: |
          cd $GITHUB_WORKSPACE
          curl -L https://github.com/FPtje/GLuaFixer/releases/download/1.18.3/glualint-1.18.3-linux.zip > glualint.zip

      - name: Extract GLuaFixer
        run: |
          cd $GITHUB_WORKSPACE
          unzip glualint.zip

      - name: Remove blacklisted folders
        run: rm -rvf $GITHUB_WORKSPACE/project/lua/entities/gmod_wire_expression2/

      - name: Test echo
        run: echo "::warning file=lua/autorun/test.lua,line=5,col=7::Unused variable: unused"

      - name: Lint with GLuaFixer
        run: |
          ./glualint --output-format github lint $GITHUB_WORKSPACE/project/lua
