name: Update Webhooker

on:
  push:
    tags:
      - '*'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: workflows

      - name: Get the workflow version
        id: workflow_versions
        run: |
          echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
          echo ::set-output name=PREVIOUS_VERSION::$(echo git describe --abbrev=0 --tags `git rev-list --tags --skip=1 --max-count=1)

      - name: Get version diff link
        env:
          PROJECT_URL=${{ github.server_url }}/${{ github.repository }}/compare/${{ steps.workflow_versions.outputs.PREVIOUS_VERSION }}..${{ steps.workflow_versions.outputs.VERSION }}
        run: echo ::set-output name=VERSION_DIFF::$(echo $PROJECT_URL )

      - name: Store newest build workflow
        id: new_workflow
        run: echo ::set-output name=WORKFLOW::$(echo $GITHUB_WORKSPACE/workflows/workflows/build_and_deploy.yml)

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'CFC-Servers/cfc_webhooker'
          token: ${{ secrets.GH_TOKEN }}
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          path: project

      - name: Update workflow version
        run: echo ${{ steps.new_workflow.outputs.WORKFLOW }} > ${{ GITHUB_WORKSPACE }}/project/.github/workflows/build_and_deploy.yml

      - name: Open PR with changes
        uses: peter-evans/create-pull-request@v3
        token: ${{ secrets.GH_TOKEN }}
        path: project
        commit-message: "Update Build & Deploy workflow to ${{ steps.workflow_versions.outputs.VERSION }}"
        branch: update-build-and-deploy-workflow
        delete-branch: true
        base: master
        title: "Update Build & Deploy workflow to ${{ steps.workflow_versions.outputs.VERSION }}"
        body: "This PR was automatically triggered due to [a change in the base Build & Deploy workflow](${{ steps.version_diff.outputs.VERSION_DIFF }})"
        reviewers: brandonsturgeon,plally
